<?php

/**
 * HubShop.ly Magento
 * 
 * Provisioning notice template.
 * 
 * @category  Template
 * @package   Groove_Hubshoply
 * @author    Groove Commerce
 * @copyright 2017 Groove Commerce, LLC. All Rights Reserved.
 *
 * LICENSE
 * 
 * The MIT License (MIT)
 * Copyright (c) 2017 Groove Commerce, LLC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

?>
<?php /* @var $this Groove_Hubshoply_Block_Adminhtml_System_Config_Field_Connector */ ?>
<tr class="system-fieldset-sub-head">
    <td colspan="5">
        <p><?php echo $this->__("It looks like you're just getting started. Make sure you are logged in as the primary store administrator. Then, click the button below to begin."); ?></p>
        <p>
            <button type="button" class="scalable" onclick="setLocation('<?php echo $this->getStartUrl(); ?>');">
                <span>
                    <span><?php echo $this->__('Start Setup'); ?></span>
                </span>
            </button>
        </p>
        <script type="text/javascript">
            if ( $('hubshoply_setup-head') ) {
                $('hubshoply_setup-head').addClassName('ready');
            }
        </script>
    </td>
</tr>